services:
  linux:
    build:
      context: ../
      dockerfile: ./docker/linux/Dockerfile
    command: bash -c "service cron start && systemctl restart rsyslog && /bin/bash"
    tty: true
    volumes:
      - ../:/project
      - ../cron/schedule:/etc/cron.d/schedule
      - ../files/logs/schedule.log:/tmp/schedule.log
      - ../files/logs/schedule.log:/tmp/schedule-error.log
